adding add_fclcm
impact-initiatives/addindicators pull request #17
Opened 2023-05-25 10:59 UTC by mhkhan27

2023-05-25 11:06 UTC, mhkhan27 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add_fclcm_phase](https://trello.com/c/tsbjXi3M/178-addfclcmphase)

2023-05-31 09:38 UTC, yannsay-impact requested changes

2023-05-31 09:38 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +
from below the error/warnings are a bit confusing as they say "The above value(s) are not specified/possibile wrong entry" there is the print, then the table, then the error. if you have time, if we can have them glue as the messages above that would help.
(test in line 16)
![image](https://github.com/impact-initiatives/addindicators/assets/79831444/cc9ff8c2-df92-47b5-ba3b-a5b71031e2d7)

2023-05-31 09:38 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +    stop("The above value(s) are not specified/possibile wrong entry")
message a bit confusing. Maybe trying to be clearer? "these values are present in the dataset but are not defined in the function arguments?

2023-05-31 09:38 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +    stop("The above value(s) are not specified/possibile wrong entry")
as above

2023-05-31 09:38 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +    warning("The above perameter(s) are not found in the dataset")
also a bit confusing, maybe trying to be clearer? "these values are defined as arguments in the function  but cannot be found in the dataset"?

2023-05-31 09:38 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +    warning("The above perameter(s) are not found in the dataset")
same

2023-05-31 09:57 UTC, yannsay-impact commented on R/add_fclcm_phase.R
> +                            lcs_cat_var = "lcs_cat_yes", # need to cross check with saeaad/ yann
I believe default is lcsi_cat

2023-06-05 08:14 UTC, yannsay-impact approved these changes

2023-06-05 08:14 UTC, merged